version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"  # Expose port 8080
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user1
      DB_PASSWORD: password123
      DB_NAME: mydatabase
    restart: on-failure

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
