apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iris-psql-claim
  labels:
    site: iris
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 30Gi