apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoex-deployment
  labels:
    app: mongoex-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoex-deployment
  template:
    metadata:
      labels:
        app: mongoex-deployment
    spec:
      containers:
        - name: mongoex
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: ME_CONFIG_MONGODB_URL
              #   value: mongodb://mongo-headless-svc:27017
              valueFrom:
               configMapKeyRef:
                 name: mongodb-configmap
                 key: database_url